app = "studenti-app-dh"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  APP_KEY = "base64:YOUR_APP_KEY"
  APP_DEBUG = "false"
  DB_CONNECTION = "mysql"
  DB_HOST = "YOUR_DB_HOST"
  DB_PORT = "3306"
  DB_DATABASE = "studiranje"
  DB_USERNAME = "stud_user"
  DB_PASSWORD = "MyN3wStrongP@ss!"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80


