app = "studenti-app-dh"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY=base64:Q/7JENfgfSXK/z94Aopu/klT4jjMaGdAoZUSUUFJYCo=
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=studiranje
DB_USERNAME=stud_user
DB_PASSWORD=MyN3wStrongP@ss!


[build]
  image = "dockerfile"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
